### ISSUE TITLE
Please remove me from the YouEarnedIt organization.

### ISSUE THREAD

**Issue by spaulsandhu** [youearnedit/dockerfiles#17]
😂   why am I still a part of this organization @jdavisyei 

![lol](https://media.giphy.com/media/HfJf5Vf9kvcTm/giphy.gif)

Miss u~

**Comment by nearbycoder** [comment]
Is this a time for all the old YEI members to chime in! 👋

**Comment by billfienberg** [comment]
👋

**Comment by jdavisyei** [comment]
Weird. Thanks for piping in. Miss you guys too.

**Comment by jdavisyei** [comment]
@spaulsandhu @nearbycoder @billfienberg you guys aren't in the org anymore. This is a public repo so you may need to unwatch it.

**Comment by ChrisBGriffith** [comment]
![image](https://user-images.githubusercontent.com/6865246/90560735-2fe98100-e165-11ea-80c2-2a3cb58ce5da.png)

**Comment by nearbycoder** [comment]
lol @jdavisyei I figured but it was still fun getting your attention
